apiVersion: v1
kind: Service
metadata:
  name: ghost-blog
spec:
  type: LoadBalancer
  selector:
    app: ghost-blog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-blog-content
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-blog-content
  labels:
    app: ghost-blog
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ghost-blog
  labels:
    app: ghost-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-blog
  template:
    metadata:
      labels:
        app: ghost-blog
    spec:
      containers:
        - name: ghost-blog
          image: ghost:2.21
          imagePullPolicy: IfNotPresent
#          command: [ "/ghost-operator"]
          env:
            - name: url
              value: http://192/168.99.100
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: content
              mountPath: /var/lib/ghost/content
      volumes:
        - name: content
          persistentVolumeClaim:
            claimName: ghost-blog-content
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ghosts.ghostcontroller.somi3k
  annotations:
    composition: Deployment, Service
spec:
  group: ghostcontroller.somi3k
  version: v1alpha1
  names:
    kind: Ghost
    plural: ghosts
  scope: Namespaced