apiVersion: ghostcontroller.somi3k/v1alpha1
kind: Ghost
metadata:
  name: ghostclient1
spec:
  deploymentName: ghostclient1
  image: ghost:2.21
  replicas: 1
#    users: [{"user": "devdatta", "password": "pass123"}, 
#            {"user": "pallavi", "password": "pass234"}]
#    databases: ["moodle"]
#    commands: [ "create table moodle_data1 (items varchar(250));",
#                "insert into moodle_data1 (items) values ('Moodle data1');",
#                "insert into moodle_data1 (items) values ('Moodle data1');",
#                "insert into moodle_data1 (items) values ('Moodle data2');",
#                "GRANT ALL PRIVILEGES ON TABLE moodle_data1 TO devdatta;",
#                "GRANT ALL PRIVILEGES ON TABLE moodle_data1 TO pallavi;"
#              ]
