/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	ghostcontrollerv1alpha1 "github.com/somi3k/ghost-operator/pkg/apis/ghostcontroller/v1alpha1"
	versioned "github.com/somi3k/ghost-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/somi3k/ghost-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/somi3k/ghost-operator/pkg/client/listers/ghostcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GhostInformer provides access to a shared informer and lister for
// Ghosts.
type GhostInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GhostLister
}

type ghostInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGhostInformer constructs a new informer for Ghost type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGhostInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGhostInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGhostInformer constructs a new informer for Ghost type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGhostInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GhostcontrollerV1alpha1().Ghosts(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GhostcontrollerV1alpha1().Ghosts(namespace).Watch(options)
			},
		},
		&ghostcontrollerv1alpha1.Ghost{},
		resyncPeriod,
		indexers,
	)
}

func (f *ghostInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGhostInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ghostInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ghostcontrollerv1alpha1.Ghost{}, f.defaultInformer)
}

func (f *ghostInformer) Lister() v1alpha1.GhostLister {
	return v1alpha1.NewGhostLister(f.Informer().GetIndexer())
}
