apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ghosts.ghostcontroller.somi3k
  annotations:
    composition: Deployment, Service
spec:
  group: ghostcontroller.somi3k
  version: v1alpha1
  names:
    kind: Ghost
    plural: ghosts
  scope: Namespaced
